---
services:
  # main services
  zookeeper:
    image: bitnami/zookeeper:3.8
  kafka:
    image: bitnami/kafka:3.7
  redis:
    image: bitnami/valkey:7.2
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
  traefik:
    image: traefik:v3.0
  maxmind-geoipupdate:
    image: ghcr.io/maxmind/geoipupdate:v7
  ipinfo-geoipupdate:
    image: ghcr.io/akvorado/ipinfo-geoipupdate:latest
    build:
      context: .
      dockerfile: Dockerfile.ipinfo-geoipupdate
  akvorado:
    image: ghcr.io/akvorado/akvorado:main

  # observability
  grafana:
    image: grafana/grafana-oss:10.2.6
  prometheus:
    image: prom/prometheus:v2.47.2
  node-exporter:
    image: prom/node-exporter:v1.7.0
  kafka-jmx-exporter:
    image: bitnami/jmx-exporter:0
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2

  # for tests
  srlinux:
    image: ghcr.io/nokia/srlinux:23.7.1
  postgres:
    image: bitnami/postgresql:16
  mysql:
    image: bitnami/mariadb:11.3
